@startuml
[*] --> Створена : Ініціалізація цілі

state Створена {
  Створена: поточна_сума = 0
}

Створена --> Накопичення : Перший внесок

state Накопичення {
  Накопичення: 0 < поточна_сума < цільова_сума
  Накопичення: update_progress()
}

Накопичення --> Накопичення : Наступні внески
Накопичення --> Скасована : Видалення цілі користувачем

state Скасована {
  Скасована: гроші повертаються на баланс
}

Накопичення --> Досягнута : поточна_сума >= цільова_сума

state Досягнута {
  Досягнута: прогрес = 100%
  Досягнута: показ привітання
}

Досягнута --> [*]
Скасована --> [*]
@enduml